---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      # black with default configs
      - id: black
        args: ["--skip-magic-trailing-comma"]
        exclude: 'python_tool_competition_2024/templates/.*'

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ["--fix"]
        exclude: "LICENSE.md"

  - repo: https://github.com/johann-petrak/licenseheaders.git
    rev: v0.8.8
    hooks:
      - id: licenseheaders
        args:
          - --tmpl
          - .gpl-v3.tmpl
          - --years
          - "2023"
          - --owner
          - Nicolas Erni
          - -n
          - python-tool-competition-2024
          - -u
          - https://github.com/ThunderKey/python-tool-competition-2024/
          - -f
        files: "^python_tool_competition_2024/.*\\.py$"
        exclude: "^python_tool_competition_2024/templates/"
